const Product = [
    // {
    //     "id": 1,
    //     "title": "iPhone 9",
    //     "description": "An apple mobile which is nothing like apple",
    // "images":"",
    //"price": 549,
    //     "discountPercentage": 12.96,
    // },
    // {
    //     "id": 2,
    //     "title": "iPhone X",
    //     "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD di…lay with OLED technology A12 Bionic chip with ...",
    //     "images": "https://i.dummyjson.com/data/products/2/1.jpg",
    //     "price": 899,
    //     "discountPercentage": 17.94,
    // },
    // {
    //     "id": 3,
    //     "title": "Samsung Universe 9",
    //     "description": "Samsung's new variant which goes beyond Galaxy to the Universe",
    //     "images": "https://i.dummyjson.com/data/products/3/1.jpg",
    //     "price": 1249,
    //     "discountPercentage": 15.46,
    // },
    // {
    //     "id": 4,
    //     "title": "OPPOF19",
    //     "description": "OPPO F19 is officially announced on April 2021.",
    // "images":"",
    //"price": 280,
    //     "discountPercentage": 17.91,
    // },
    // {
    //     "id": 5,
    //     "title": "Huawei P30",
    //     "description": "Huawei’s re-badged P30 Pro New Edition was officia…ny and now the device has made its way to the UK.",
    // "images":"",
    //"price": 499,
    //     "discountPercentage": 10.58,
    // },
    // {
    //     "id": 6,
    //     "title": "MacBook Pro",
    //     "description": "MacBook Pro 2021 with mini-LED display may launch between September, November",
    // "images":"",
    //"price": 1749,
    //     "discountPercentage": 11.02,
    // },
    // {
    //     "id": 7,
    //     "title": "Samsung Galaxy Book",
    //     "description": "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip,8GB of RAM Launched",
    // "images":"", 
    // "price": 1499, "discountPercentage": 4.15,
    // },
    // {
    //     "id": 8,
    //     "title": "Microsoft Surface Laptop 4",
    //     "description": "Style and speed. Stand out on HD video calls backe…o Mics. Capture ideas on the vibrant touchscreen.",
    // "images":"",
    //"price": 1499,
    //     "discountPercentage": 10.23,
    // },
    // {
    //     "id": 9,
    //     "title": "Infinix INBOOK",
    //     "description": "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
    // "images":"",
    //"price": 1099,
    //     "discountPercentage": 11.83,
    // },
    // {
    //     "id": 10,
    //     "title": "HP Pavilion 15-DK1056WM",
    //     "description": "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5 8GB 256GB SSD GTX 1650 4GB Windows 10", 
    // "images":"",
    // "price": 1099, "discountPercentage": 6.18,
    // },
    {
        "id": 11,
        "title": "perfume Oil",
        "description": "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
        "images": "https://i.dummyjson.com/data/products/11/1.jpg",
        "price": 13,
        "discountPercentage": 8.4,
    },
    // {
    //     "id": 12,
    //     "title": "Brown Perfume",
    //     "description": "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    // "images":"",
    //"price": 40,
    //     "discountPercentage": 15.66,
    // },
    // {
    //     "id": 13,
    //     "title": "Fog Scent Xpressio Perfume",
    //     "description": "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
    // "images":"",
    //"price": 13,
    //     "discountPercentage": 8.14,
    // },
    {
        "id": 14,
        "title": "Non-Alcoholic Concentrated Perfume Oil",
        "description": "Original Al Munakh® by Mahal Al Musk | Our Impress…mate | 6ml Non-Alcoholic Concentrated Perfume Oil",
        "images": "https://i.dummyjson.com/data/products/14/1.jpg",
        "price": 120,
        "discountPercentage": 15.6,
    },
    // {
    //     "id": 15,
    //     "title": "Eau De Perfume Spray",
    //     "description": "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
    //     "images": "https://i.dummyjson.com/data/products/15/1.jpg",
    //     "price": 30,
    //     "discountPercentage": 10.99,
    // },
    {
        "id": 16,
        "title": "Hyaluronic Acid Serum",
        "description": "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
        "images": "https://i.dummyjson.com/data/products/16/1.png",
        "price": 19,
        "discountPercentage": 13.31,
    },
    // {
    //     "id": 17,
    //     "title": "Tree Oil 30ml",
    //     "description": "Tea tree oil contains a number of compounds, inclu…l, that have been shown to kill certain bacteria,",
    //     "images": "https://i.dummyjson.com/data/products/17/1.jpg",
    //     "price": 12,
    //     "discountPercentage": 4.09,
    // },
    {
        "id": 18,
        "title": "Oil Free Moisturizer 100ml",
        "description": "Dermive Oil Free Moisturizer with SPF 20 is specif…ated with ceramides, hyaluronic acid & sunscreen.",
        "images": "https://i.dummyjson.com/data/products/18/1.jpg",
        "price": 40,
        "discountPercentage": 13.1,
    },
    {
        "id": 19,
        "title": "Skin Beauty Serum.",
        "description": "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
        "images": "https://i.dummyjson.com/data/products/19/1.jpg",
        "price": 46,
        "discountPercentage": 10.68,
    },
    {
        "id": 20,
        "title": "Freckle Treatment Cream- 15gm",
        "description": "Fair & Clear is Pakistan's only pure Freckle cream…ercury level is 0%, so there are no side effects.",
        "images": "https://i.dummyjson.com/data/products/20/1.jpg",
        "price": 70,
        "discountPercentage": 16.99,
    },
    // {
    //     "id": 21,
    //     "title": "- Daal Masoor 500 grams",
    //     "description": "Fine quality Branded Product Keep in a cool and dry place",
    // "images":"",
    //"price": 20,
    //     "discountPercentage": 4.81,
    // },
    {
        "id": 22,
        "title": "Elbow Macaroni - 400 gm",
        "description": "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
        "images": "https://i.dummyjson.com/data/products/22/1.jpg",
        "price": 14,
        "discountPercentage": 15.58,
    },
    {
        "id": 23,
        "title": "Orange Essence Food Flavou",
        "description": "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
        "images": "https://i.dummyjson.com/data/products/23/1.jpg",
        "price": 14,
        "discountPercentage": 8.04,
    },
    {
        "id": 24,
        "title": "cereals muesli fruit nuts",
        "description": "original fauji cereal muesli 250gm box pack origin…l break fast faujicereals cerels cerel foji fouji",
        "images": "https://i.dummyjson.com/data/products/24/1.jpg",
        "price": 46,
        "discountPercentage": 16.8,
    },
    {
        "id": 25,
        "title": "Gulab Powder 50 Gram",
        "description": "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
        "images": "https://i.dummyjson.com/data/products/25/1.png",
        "price": 70,
        "discountPercentage": 13.58,
    },
    {
        "id": 26,
        "title": "Plant Hanger For Home",
        "description": "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
        "images": "https://i.dummyjson.com/data/products/26/1.jpg",
        "price": 41,
        "discountPercentage": 17.86,
    },
    // {
    //     "id": 27,
    //     "title": "Flying Wooden Bird",
    //     "description": "Package Include 6 Birds with Adhesive Tape Shape:ooden Birds Material: Wooden MDF, Laminated 3.5mm",
    // "images":"",
    //"price": 51,
    //     "discountPercentage": 15.58,
    // },
    {
        "id": 28,
        "title": "3D Embellishment Art Lamp",
        "description": "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
        "images": "https://i.dummyjson.com/data/products/28/1.jpg",
        "price": 20,
        "discountPercentage": 16.49,
    },
    {
        "id": 29,
        "title": "Handcraft Chinese style",
        "description": "Handcraft Chinese style art luxury palace hotel vi…on home decor ceramic vase with brass fruit plate",
        "images": "https://i.dummyjson.com/data/products/29/1.jpg",
        "price": 60,
        "discountPercentage": 15.34,
    },
    {
        "id": 30,
        "title": "Key Holder",
        "description": "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
        "images": "https://i.dummyjson.com/data/products/30/1.jpg",
        "price": 30,
        "discountPercentage": 2.92,
    }
]

export default Product